import { loadStylesheet } from "../../platform/stylesheet.js";
import { escapeHtml, sanitizeImageUrl, sanitizeUrl } from "../../shared/dom.js";
import { t } from "../../i18n.js";
let markdownLoading; let mermaidLoading; let katexLoading; let highlightLoading; let parser;
function loadScript(src,key){const old=document.querySelector(`script[data-writer-library="${key}"]`);if(old?.dataset.ready==="true")return Promise.resolve();if(old)return new Promise((ok,no)=>{old.addEventListener("load",ok,{once:true});old.addEventListener("error",no,{once:true});});return new Promise((ok,no)=>{const s=document.createElement("script");s.src=src;s.defer=true;s.dataset.writerLibrary=key;s.onload=()=>{s.dataset.ready="true";ok();};s.onerror=no;document.head.append(s);});}
async function markdown(){markdownLoading??=Promise.all(["markdown-it","markdown-it-task-lists","markdown-it-footnote","markdown-it-deflist","markdown-it-mark","markdown-it-sub","markdown-it-sup"].map(n=>loadScript(`./js/vendor/markdown/${n}.min.js`,n))).then(()=>{parser=window.markdownit({html:true,linkify:true,typographer:true}).use(window.markdownitTaskLists).use(window.markdownitFootnote).use(window.markdownitDeflist).use(window.markdownitMark).use(window.markdownitSub).use(window.markdownitSup);const image=parser.renderer.rules.image;parser.renderer.rules.image=(tokens,i,o,e,self)=>{const token=tokens[i];const src=sanitizeImageUrl(token.attrGet("src"));return src?`<img src="${escapeHtml(src)}" alt="${escapeHtml(token.content)}">`:escapeHtml(token.content);};parser.renderer.rules.link_open=(tokens,i,o,e,self)=>{const href=sanitizeUrl(tokens[i].attrGet("href"));if(!href)return "";tokens[i].attrSet("href",href);tokens[i].attrSet("rel","noopener");return self.renderToken(tokens,i,o);};return parser;});return markdownLoading;}
async function mermaid(){mermaidLoading??=loadScript("./js/vendor/mermaid.min.js","mermaid").then(()=>{window.mermaid.initialize({startOnLoad:false,securityLevel:"strict",theme:"base"});return window.mermaid;});return mermaidLoading;}
async function katex(){if(!document.querySelector("link[data-writer-katex]")){const l=document.createElement("link");l.rel="stylesheet";l.href="./js/vendor/katex/katex.min.css";l.dataset.writerKatex="true";document.head.append(l);}katexLoading??=loadScript("./js/vendor/katex/katex.min.js","katex").then(()=>window.katex);return katexLoading;}
async function highlighter(){highlightLoading??=Promise.all([loadScript("./js/vendor/highlight/highlight.min.js","highlight"),loadStylesheet("./js/vendor/highlight/default.min.css","writer-highlight")]).then(()=>loadScript("./js/vendor/highlight/powershell.min.js","highlight-powershell")).then(()=>window.hljs);return highlightLoading;}
function frontMatterMarkup(metadata) {
  const lines=String(metadata??"").split("\n");
  const rows=[];
  for(let index=0;index<lines.length;index+=1){
    const match=lines[index].match(/^([^:#][^:]*):\s*(.*)$/);
    if(!match)continue;
    const [,key,rawValue]=match;
    const values=[];
    if(rawValue.trim())values.push(rawValue.trim());
    while(index+1<lines.length&&/^\s+-\s+/.test(lines[index+1]))values.push(lines[++index].replace(/^\s+-\s+/,"").trim());
    const value=key.trim().toLowerCase()==="tags"
      ? values.map((tag)=>`<span class="writer-inline-tag">${escapeHtml(tag.replace(/`/g,"").trim())}</span>`).join(" ")
      : escapeHtml(values.join(", "));
    rows.push(`<dt>${escapeHtml(key.trim())}</dt><dd>${value}</dd>`);
  }
  return `<section class="writer-frontmatter"><strong>Front matter</strong><dl>${rows.join("")}</dl></section>`;
}
function protectCodeFences(source,stash) {
  const lines=String(source??"").split("\n");
  const output=[];
  for(let index=0;index<lines.length;index+=1){
    const opening=lines[index].match(/^(`{3,})([^`]*)$/);
    if(!opening){output.push(lines[index]);continue;}
    const fence=opening[1];
    const language=opening[2].trim().split(/\s+/,1)[0].toLowerCase();
    let closing=index+1;
    while(closing<lines.length&&!new RegExp("^`{"+fence.length+",}\\s*$").test(lines[closing]))closing+=1;
    if(closing===lines.length){output.push(lines[index]);continue;}
    const body=lines.slice(index+1,closing).join("\n");
    if(["mermaid","plantuml","graphviz"].includes(language))output.push(stash(`<div class="writer-diagram" data-diagram-kind="${language}" data-diagram="${escapeHtml(body.trim())}"></div>`));
    else {const className=language?` class="language-${escapeHtml(language)}"`:"";output.push(stash(`<pre><code${className}>${escapeHtml(body)}</code></pre>`));}
    index=closing;
  }
  return output.join("\n");
}
function blocks(source){
  const values=[];
  const stash=(html)=>{const token=`@@K${values.length}@@`;values.push(html);return token;};
  let text=protectCodeFences(source,stash);
  const front=text.match(/^(---|\+\+\+|;;;)\n([\s\S]*?)\n\1\n?/);
  if(front){text=stash(frontMatterMarkup(front[2]))+text.slice(front[0].length);}
  text=text.replace(/\\+\n/g,()=>stash("<br>")).replace(/>>>\n([\s\S]*?)\n>>>/g,(_,body)=>stash(`<blockquote class="writer-multiline-quote">${escapeHtml(body)}</blockquote>`)).replace(/(?:^|\n)---\n([A-Za-z][^\n]*:[\s\S]*?)\n---(?=\n|$)/g,(_,metadata)=>`\n${stash(frontMatterMarkup(metadata))}\n`).replace(/!\[([^\]]*)\]\(([^)]+)\)(?:\{([^}]*)\})?/g,(_,alt,url,dimensions)=>{const source=sanitizeImageUrl(url);if(!source)return alt;const attributes=String(dimensions??"").match(/(width|height)=(\d+(?:px|%)?)/g)?.map(part=>part.replace('=','="')+'"').join(" ")??"";const media=/\.(mp4|webm|ogv)(?:[?#]|$)/i.test(source)?`<video controls ${attributes}><source src="${escapeHtml(source)}"></video>`:/\.(mp3|wav|ogg|m4a)(?:[?#]|$)/i.test(source)?`<audio controls ${attributes}><source src="${escapeHtml(source)}"></audio>`:`<img src="${escapeHtml(source)}" alt="${escapeHtml(alt)}" ${attributes}>`;return stash(media);}).replace(/\$\$([\s\S]*?)\$\$/g,(_,m)=>stash(`<div class="writer-math writer-math-block" data-math="${escapeHtml(m.trim())}"></div>`)).replace(/\$`([^`\n]+)`\$/g,(_,m)=>stash(`<span class="writer-math" data-math="${escapeHtml(m.trim())}"></span>`)).replace(/\$([^$\n]+)\$/g,(_,m)=>stash(`<span class="writer-math" data-math="${escapeHtml(m.trim())}"></span>`)).replace(/##([^#\n]+?)##/g,(_,raw)=>{const label=String(raw).replace(/`/g,"").trim();return label?stash(`<span class="writer-inline-tag">${escapeHtml(label)}</span>`):"";});
  return {text,values};
}
export function renderMarkdown(source){const {text,values}=blocks(source);if(!parser)return `<p>${escapeHtml(text).replace(/\n/g,"<br>")}</p>`;return parser.render(text).replace(/<p>@@K(\d+)@@<\/p>|@@K(\d+)@@/g,(_,first,second)=>values[Number(first??second)]??"");}
function applyCallouts(root){const definitions={NOTE:["ℹ️","Note"],TIP:["💡","Tip"],IMPORTANT:["❗","Important"],WARNING:["⚠️","Warning"],CAUTION:["⛔","Caution"]};const french={NOTE:"Note",TIP:"Astuce",IMPORTANT:"Important",WARNING:"Avertissement",CAUTION:"Attention"};for(const quote of root.querySelectorAll("blockquote")){const first=quote.firstElementChild;const match=first?.textContent.match(/^\s*\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*/i);if(!match)continue;const kind=match[1].toUpperCase();const [emoji,label]=definitions[kind];first.textContent=first.textContent.replace(match[0],"");if(!first.textContent.trim())first.remove();const callout=document.createElement("aside");callout.className=`writer-callout writer-callout-${kind.toLowerCase()}`;const title=document.createElement("strong");title.className="writer-callout-title";title.textContent=`${emoji} ${document.documentElement.lang === "fr" ? french[kind] : label}`;callout.append(title,...[...quote.childNodes]);quote.replaceWith(callout);}}
function sanitizeHtml(root){for(const node of root.querySelectorAll("script,style,iframe,object,embed,form"))node.remove();for(const element of root.querySelectorAll("*")){for(const attribute of [...element.attributes]){if(/^on/i.test(attribute.name)||(["href","src"].includes(attribute.name)&&!(element.tagName==="IMG"?sanitizeImageUrl(attribute.value):sanitizeUrl(attribute.value))))element.removeAttribute(attribute.name);}}}
function applyReferences(root){for(const cell of root.querySelectorAll("td,th")){const walker=document.createTreeWalker(cell,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const value=node.nodeValue;if(!/\[!NOTE\]|\[\^1\]|\[1\]/.test(value))continue;const fragment=document.createDocumentFragment();let cursor=0;value.replace(/\[!NOTE\]|\[\^1\]|\[1\]/g,(match,index)=>{fragment.append(value.slice(cursor,index));const ref=document.createElement("sup");const link=document.createElement("a");link.href=(match==="[1]"||match==="[^1]")?"#fn1":"#writer-note-note";link.textContent=(match==="[1]"||match==="[^1]")?"1":"NOTE";ref.append(link);fragment.append(ref);cursor=index+match.length;});fragment.append(value.slice(cursor));node.replaceWith(fragment);}}}
function applyEmoji(root){const emoji={rocket:"🚀",tada:"🎉",fire:"🔥",bug:"🐛",warning:"⚠️",white_check_mark:"✅",x:"❌"};const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())if(!walker.currentNode.parentElement.closest("code,pre"))nodes.push(walker.currentNode);for(const node of nodes)node.nodeValue=node.nodeValue.replace(/:([a-z_]+):/g,(all,name)=>emoji[name]??all);}
function applyToc(root){const marker=[...root.querySelectorAll("p")].find(node=>node.textContent.trim()==="[[TOC]]"||node.textContent.trim()==="[TOC]");if(!marker)return;const headings=[...root.querySelectorAll("h1,h2,h3,h4,h5,h6")];const toc=document.createElement("nav");toc.className="writer-toc";toc.setAttribute("aria-label","Table of contents");const list=document.createElement("ol");headings.forEach((heading,index)=>{const id=heading.id||`writer-heading-${index+1}`;heading.id=id;const item=document.createElement("li");item.style.setProperty("--toc-level",heading.tagName.slice(1));const link=document.createElement("a");link.href=`#${id}`;link.textContent=heading.textContent;item.append(link);list.append(item);});toc.append(list);marker.replaceWith(toc);}
function applyInlineDiff(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())if(!walker.currentNode.parentElement.closest("code,pre"))nodes.push(walker.currentNode);for(const node of nodes){const value=node.nodeValue;if(!/[{][+]|[[][-]|[[]\+/.test(value))continue;const fragment=document.createDocumentFragment();let cursor=0;value.replace(/\{\+([\s\S]*?)\+\}|\[\+([\s\S]*?)\+\]|\[\-([\s\S]*?)\-\]/g,(match,curlyAdded,bracketAdded,removed,index)=>{const added=curlyAdded??bracketAdded;fragment.append(value.slice(cursor,index));const span=document.createElement("ins");span.className=added===undefined?"writer-diff-removed":"writer-diff-added";span.textContent=added??removed;fragment.append(span);cursor=index+match.length;});fragment.append(value.slice(cursor));node.replaceWith(fragment);}}
function applyWriterExtensions(root){for(const code of root.querySelectorAll("code:not(pre code)")){const value=code.textContent.trim();const color=/^(#[0-9a-f]{3,8}|rgba?\([^)]*\)|hsla?\([^)]*\))$/i.test(value)?value:"";if(color){const chip=document.createElement("span");chip.className="writer-color-chip";chip.style.backgroundColor=color;chip.title=value;const group=document.createElement("span");group.className="writer-color-value";code.before(group);group.append(code,chip);}}for(const paragraph of [...root.querySelectorAll("p")]){const match=paragraph.textContent.match(/^([^:\n]+?)\s*:\s*([^:\n]+?)\s*:\s*(.+)$/);if(!match)continue;const list=document.createElement("dl");list.className="writer-description-list";const term=document.createElement("dt");term.textContent=match[1];list.append(term);for(const definition of [match[2],match[3]]){const item=document.createElement("dd");item.textContent=definition.trim();list.append(item);}paragraph.replaceWith(list);}for(const paragraph of [...root.querySelectorAll("p")]){const value=paragraph.textContent.trim();if(!value.startsWith(">>>"))continue;const quote=document.createElement("blockquote");quote.className="writer-multiline-quote";quote.textContent=value.replace(/^>>>\s*\n?|\n?>>>$/g,"");paragraph.replaceWith(quote);}}
function applySyntaxHighlighting(root,hljs){const aliases={js:"javascript",jsx:"javascript",ts:"typescript",tsx:"typescript",py:"python",ps1:"powershell",pwsh:"powershell",sh:"bash",shell:"bash",yml:"yaml",html:"xml",svg:"xml"};for(const code of root.querySelectorAll("pre code")){const declared=[...code.classList].find(name=>name.startsWith("language-"))?.slice(9).toLowerCase();const language=aliases[declared]??declared;try{const result=language&&hljs.getLanguage(language)?hljs.highlight(code.textContent,{language,ignoreIllegals:true}):hljs.highlightAuto(code.textContent);code.innerHTML=result.value;code.classList.add("hljs");if(result.language)code.dataset.highlightLanguage=result.language;}catch{}}}
async function copyCode(button) {
  const code=button.closest("pre")?.querySelector("code")?.textContent??"";
  try { if(!navigator.clipboard?.writeText)throw new Error("Clipboard API unavailable");await navigator.clipboard.writeText(code); } catch { const area=document.createElement("textarea");area.value=code;area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();document.execCommand("copy");area.remove(); }
  button.classList.add("is-copied");setTimeout(()=>button.classList.remove("is-copied"),1200);
}
function addCodeCopyButtons(root){for(const pre of root.querySelectorAll("pre")){if(!pre.querySelector(":scope > code")||pre.querySelector("[data-writer-copy-code]"))continue;const button=document.createElement("button");button.type="button";button.className="writer-code-copy";button.dataset.writerCopyCode="";button.setAttribute("aria-label",t("writerCopyCode"));button.title=t("writerCopyCode");button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="8" y="8" width="11" height="12" rx="1"/><path d="M5 16H4a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1"/></svg>';button.addEventListener("click",()=>{copyCode(button);});pre.append(button);}}
function themeValue(root,name,fallback) {
  return getComputedStyle(root).getPropertyValue(name).trim() || fallback;
}
function configureDiagramTheme(mermaidInstance,root) {
  const background=themeValue(root,"--background","#ffffff");
  const surface=themeValue(root,"--landscape-filled","#ffffff");
  const secondary=themeValue(root,"--landscape-secondary","#f2f2f2");
  const text=themeValue(root,"--inactive-primary","#1f2937");
  const accent=themeValue(root,"--focus",themeValue(root,"--accent","#4f46e5"));
  const border=themeValue(root,"--landscape-delimited",accent);
  mermaidInstance.initialize({startOnLoad:false,securityLevel:"strict",theme:"base",themeVariables:{background,primaryColor:surface,primaryTextColor:text,primaryBorderColor:border,secondaryColor:secondary,secondaryTextColor:text,secondaryBorderColor:border,tertiaryColor:background,tertiaryTextColor:text,tertiaryBorderColor:border,lineColor:accent,mainBkg:surface,secondBkg:secondary,tertiaryBkg:background,nodeBorder:border,clusterBkg:background,clusterBorder:border}});
}
function diagramSource(node){const source=node.dataset.diagram??"";if(node.dataset.diagramKind==="plantuml"){const lines=source.split("\n").map(line=>line.match(/^\s*(.+?)\s*->\s*(.+?)\s*:\s*(.+)$/)).filter(Boolean).map(([,from,to,label])=>`${from.trim()}->>${to.trim()}: ${label.trim()}`);return `sequenceDiagram\n${lines.join("\n")}`;}if(node.dataset.diagramKind==="graphviz"){const edges=[...source.matchAll(/([A-Za-z0-9_]+)\s*->\s*([A-Za-z0-9_]+)/g)].map(([,from,to])=>`${from} --> ${to}`);return `flowchart TD\n${edges.join("\n")}`;}return source;}
export async function enhanceWriterPreview(root){await markdown();if(root.dataset.writerMarkdown!==undefined)root.innerHTML=renderMarkdown(root.dataset.writerMarkdown);sanitizeHtml(root);applyCallouts(root);applyToc(root);applyInlineDiff(root);applyWriterExtensions(root);applyReferences(root);applyEmoji(root);const[m,k,h]=await Promise.all([mermaid(),katex(),highlighter().catch(()=>null)]);if(h)applySyntaxHighlighting(root,h);addCodeCopyButtons(root);for(const n of root.querySelectorAll(".writer-math"))try{k.render(n.dataset.math??"",n,{displayMode:n.classList.contains("writer-math-block"),throwOnError:false,trust:false});}catch{n.textContent=n.dataset.math??"";}configureDiagramTheme(m,root);for(const n of root.querySelectorAll(".writer-diagram"))try{const{svg}=await m.render(`writer-${Math.random().toString(36).slice(2)}`,diagramSource(n));n.innerHTML=svg;}catch{n.textContent=n.dataset.diagram??"";}}
